name: dl-omr
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - python-dotenv
  - requests
  - graphviz
  - python-graphviz
  - jupyter
  - pandas
  - matplotlib
  - plotly
  - scikit-learn
  - tensorflow
  - pytorch
  - torchvision
  - opencv
  - seaborn
