name: dl-omr
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - python-dotenv
  - requests
  - jupyter
  - pandas
  - matplotlib
  - tensorflow
  - opencv
  # - scikit-learn
  # - graphviz
  # - python-graphviz
  # - plotly
  # - pytorch
  # - torchvision
  # - seaborn
  # - visualkeras
